// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlXpIDPpxlHD1CgCJlw-ADfS107vcEJg',
    appId: '1:507894371327:web:a17a3ba7a45f63de23cdca',
    messagingSenderId: '507894371327',
    projectId: 'zomorod',
    authDomain: 'zomorod.firebaseapp.com',
    storageBucket: 'zomorod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtd8OVfOlEcjnHfZx8JoWC6jE3glo5Tic',
    appId: '1:507894371327:android:27fd0b6ba11c99f423cdca',
    messagingSenderId: '507894371327',
    projectId: 'zomorod',
    storageBucket: 'zomorod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJXXUY2pzHT72VGciEzKe3e9ma4WhRm4',
    appId: '1:507894371327:ios:7bda3105e871a13123cdca',
    messagingSenderId: '507894371327',
    projectId: 'zomorod',
    storageBucket: 'zomorod.appspot.com',
    iosClientId: '507894371327-04lbjfg2erpp5adth8d66pq42795be99.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomorod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJXXUY2pzHT72VGciEzKe3e9ma4WhRm4',
    appId: '1:507894371327:ios:7bda3105e871a13123cdca',
    messagingSenderId: '507894371327',
    projectId: 'zomorod',
    storageBucket: 'zomorod.appspot.com',
    iosClientId: '507894371327-04lbjfg2erpp5adth8d66pq42795be99.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomorod',
  );
}
